Two polybar plugins added
TiagoDanin/Awesome-Polybar pull request #12
Opened 2019-10-09 20:54 UTC by deepak2431

2019-10-10 20:16 UTC, deepak2431 commented
@TiagoDanin Hi, Please review it.
Thanks!

2019-10-10 23:30 UTC, TiagoDanin requested changes
Add the plugins in README

2019-10-11 17:51 UTC, deepak2431 commented
@TiagoDanin I have added plugins to the readme. Please review it.
Thanks!

2019-10-13 03:30 UTC, TiagoDanin approved these changes

2019-10-13 03:30 UTC, merged